// File generated by FlutterFire CLI.
// This is a placeholder - replace with your actual Firebase configuration
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVvZ3b9Bd3heHokhIzQD1XURcRLuqbdw',
    appId: '1:276445026103:android:b0f82d30263e42014d6cb2',
    messagingSenderId: '276445026103',
    projectId: 'gubat-messages',
    storageBucket: 'gubat-messages.firebasestorage.app',
  );

  // Note: Replace the placeholder values above with your actual Firebase project configuration
  // You can get these values from your Firebase Console > Project Settings > General > Your apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpf0RQSSDaoJx1T2LJCDqF_TT86ru8-yc',
    appId: '1:276445026103:web:1dd5048b563cfe544d6cb2',
    messagingSenderId: '276445026103',
    projectId: 'gubat-messages',
    authDomain: 'gubat-messages.firebaseapp.com',
    storageBucket: 'gubat-messages.firebasestorage.app',
    measurementId: 'G-Y989WFDH4J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUC-3iVcbgnC13o5tzjKRpt_Bc3YjpLnk',
    appId: '1:276445026103:ios:dabc08d04a00ea154d6cb2',
    messagingSenderId: '276445026103',
    projectId: 'gubat-messages',
    storageBucket: 'gubat-messages.firebasestorage.app',
    iosBundleId: 'com.example.gubatMessages',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUC-3iVcbgnC13o5tzjKRpt_Bc3YjpLnk',
    appId: '1:276445026103:ios:dabc08d04a00ea154d6cb2',
    messagingSenderId: '276445026103',
    projectId: 'gubat-messages',
    storageBucket: 'gubat-messages.firebasestorage.app',
    iosBundleId: 'com.example.gubatMessages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpf0RQSSDaoJx1T2LJCDqF_TT86ru8-yc',
    appId: '1:276445026103:web:62c0a7b1c358ec574d6cb2',
    messagingSenderId: '276445026103',
    projectId: 'gubat-messages',
    authDomain: 'gubat-messages.firebaseapp.com',
    storageBucket: 'gubat-messages.firebasestorage.app',
    measurementId: 'G-QWRWWMZBWW',
  );

}